Server:
  RunMode: debug
  HttpPort: 8000
  ReadTimeout: 60
App:
  DefaultPageSize: 10
  MaxPageSize: 100
  LogSavePath: storage/logs
  LogFileName: app
  LogFileExt: .log
Database:
  DBType: mysql
  Username: cms.nf305.com
  Password: 87wrWj3MKcLXirS2
  Host: 39.101.214.179:3306
  DBName: cms.nf305.com
  TablePrefix: dp_
  Charset: utf8
  MaxIdleConns: 10
  MaxOpenConns: 30
Email:
  Host: smtp.qq.com
  Port: 465
  UserName: xxx@qq.com
  Password: xxxxx
  IsSSL: true
  From: xxxx@qq.com
  To:
    - xxxx@qq.com
JWT:
  Secret: eddycjy
  Issuer: blog-serice
  Exipre: 7200